[tool.black]
line-length = 100
target-version = ["py311"]
include = '\\.pyi?$'
extend-exclude = [
  "^app/stores/.*",
]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["app/stores"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
  "SIM" # flake8-simplify
]
ignore = []

